// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXqgRH_9MoO3rJX8IWhVwJ93If_1spMEY',
    appId: '1:800022951078:web:dd405dee01e67bbfa6f067',
    messagingSenderId: '800022951078',
    projectId: 'teamproject-972bd',
    authDomain: 'teamproject-972bd.firebaseapp.com',
    storageBucket: 'teamproject-972bd.appspot.com',
    measurementId: 'G-BZXRREB0FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbL59E_-pT3MN4niu-PFq6XM4fRhRBpns',
    appId: '1:800022951078:android:b2a692e3863c5a88a6f067',
    messagingSenderId: '800022951078',
    projectId: 'teamproject-972bd',
    storageBucket: 'teamproject-972bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5dshJmE39qr68c0lR-2CG4SWGwAXjqzg',
    appId: '1:800022951078:ios:27b9e516cdfeaadaa6f067',
    messagingSenderId: '800022951078',
    projectId: 'teamproject-972bd',
    storageBucket: 'teamproject-972bd.appspot.com',
    iosClientId: '800022951078-scendrp4u29aclcf28o04mlohi3e1h9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterteamproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5dshJmE39qr68c0lR-2CG4SWGwAXjqzg',
    appId: '1:800022951078:ios:27b9e516cdfeaadaa6f067',
    messagingSenderId: '800022951078',
    projectId: 'teamproject-972bd',
    storageBucket: 'teamproject-972bd.appspot.com',
    iosClientId: '800022951078-scendrp4u29aclcf28o04mlohi3e1h9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterteamproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXqgRH_9MoO3rJX8IWhVwJ93If_1spMEY',
    appId: '1:800022951078:web:28d6f45cccaa5071a6f067',
    messagingSenderId: '800022951078',
    projectId: 'teamproject-972bd',
    authDomain: 'teamproject-972bd.firebaseapp.com',
    storageBucket: 'teamproject-972bd.appspot.com',
    measurementId: 'G-1JERC2BR74',
  );

}